[package]
name = "prost_error_details"
version = "0.1.0"
authors = ["peter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.6"
prost-types = "0.6"

[build-dependencies]
prost-build = "0.6"